# Sesi 3 — 3.2 Data Cleaning

Ikuti live coding di sini. Isi bagian `# TODO:` sesuai instruksi di tiap cell

Dataset: `orders_dirty.csv`.

## 1. Setup + load dataset

In [16]:
import pandas as pd

# TODO: load orders_dirty.csv ke df
df = pd.read_csv("../datasets/orders_dirty.csv")
print("Shape awal:", df.shape)
df.head()

Shape awal: (508, 13)

,order_id,order_date,customer_name,email,segment,city,category,product_name,price_idr,quantity,discount,rating,product_review
0,ORD-00059,2024-08-13,Putri Rahman,putri.rahman15@yahoo.com,Consumer,Makassar,Rumah,Lampu Meja,814512,3,0.00,3.5,"Recommended seller, packing rapi"
1,ORD-00280,2024-03-14,Indah Hidayat,indah.hidayat51@gmail.com,Corporate,Medan,ELEKTRONIK,Laptop,5686210,10,0.20,4.4,Harga terjangkau dan barang berkualitas
2,ORD-00342,2024-10-16,Sari Pratama,sari.pratama32@yahoo.com,Consumer,Makassar,Makanan,Teh Celup,105549,6,0.10,3.3,"Puas dengan pembelian ini, akan beli lagi"
3,ORD-00430,2024-11-22,Oki Lestari,oki.lestari24@gmail.com,Consumer,Malang,Kesehatan,Hand Sanitizer,168548,3,0.25,3.4,Sesuai ekspektasi
4,ORD-00367,"Jun 27, 2024",Rina Utami,rina.utami59@gmail.com,Corporate,Malang,makanan,Teh Celup,101088,5,0.00,4.2,"Pengiriman cepat, kualitas mantap"

## 2. Inspeksi awal

In [17]:
# TODO: cetak df.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 508 entries, 0 to 507
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        508 non-null    str
 1   order_date      508 non-null    str
 2   customer_name   508 non-null    str
 3   email           508 non-null    str
 4   segment         508 non-null    str
 5   city            500 non-null    str
 6   category        508 non-null    str
 7   product_name    508 non-null    str
 8   price_idr       508 non-null    int64
 9   quantity        508 non-null    int64
 10  discount        508 non-null    float64
 11  rating          495 non-null    float64
 12  product_review  502 non-null    str
dtypes: float64(2), int64(2), str(9)
memory usage: 51.7 KB

In [18]:
# TODO: cetak df.describe()
df.describe()

          price_idr    quantity    discount      rating
count  5.080000e+02  508.000000  508.000000  495.000000
mean   1.030836e+06    7.488189    0.108366    3.997374
std    1.712265e+06   44.167489    0.089563    0.722970
min   -5.000000e+04    1.000000    0.000000   -1.000000
25%    1.326742e+05    3.000000    0.000000    3.500000
50%    3.350155e+05    5.000000    0.100000    4.000000
75%    1.037040e+06    8.000000    0.200000    4.500000
max    7.765195e+06  999.000000    0.250000   12.500000

In [19]:
# TODO: hitung null per kolom pakai df.isna().sum()
df.isna().sum()

order_id           0
order_date         0
customer_name      0
email              0
segment            0
city               8
category           0
product_name       0
price_idr          0
quantity           0
discount           0
rating            13
product_review     6
dtype: int64

## 3. Tangani missing values

Aturan praktis:
- **Drop rows** kalau hanya sedikit baris terpengaruh, sisa data masih cukup
- **Fill** / **imputasi** kalau proporsi missing besar, drop malah bikin data terlalu kecil

In [24]:
# TODO: fill kolom rating dengan mean dari kolom rating
mean_rating = df["rating"].mean() # mencari mean dari kolom "rating"
print(mean_rating)
df["rating"] = df["rating"].fillna(mean_rating)

3.999383983572896

In [20]:
# TODO: drop baris tanpa city — pakai df.dropna(subset=["city"])
print("Jumlah baris sebelum drop city", len(df))
df = df.dropna(subset=["city"])
print("Jumlah baris setelah drop city", len(df))

Jumlah baris sebelum drop city 508
Jumlah baris setelah drop city 500

In [22]:
# TODO: fill product_review yang null dengan string kosong ""
# df[df["product_review"].isna()]
df["product_review"] = df["product_review"].fillna("")

In [29]:
help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(value: 'Hashable | Mapping | Series | DataFrame', *, axis: 'Axis | None' = None, inplace: 'bool' = False, limit: 'int | None' = None) -> 'Self' method of pandas.DataFrame instance
    Fill NA/NaN values with `value`.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        This is the maximum number of entries along the entire axis
        where NaNs will be filled. Must be greater than 0 if not None.

    Returns
    -------
    Series/DataFrame
        Object with missing values filled.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Notes
    -----
    For non-object dtype, ``value=None`` will use the NA value of the dtype.
    See more details in the :ref:`Filling missing data<missing_data.fillna>`
    section.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     [
    ...         [np.nan, 2, np.nan, 0],
    ...         [3, 4, np.nan, 1],
    ...         [np.nan, np.nan, np.nan, np.nan],
    ...         [np.nan, 3, np.nan, 4],
    ...     ],
    ...     columns=list("ABCD"),
    ... )
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [25]:
df.isna().sum()

order_id          0
order_date        0
customer_name     0
email             0
segment           0
city              0
category          0
product_name      0
price_idr         0
quantity          0
discount          0
rating            0
product_review    0
dtype: int64

## 4. Hapus duplicates

In [30]:
# TODO: cetak df.duplicated().sum()
print("Jumlah data duplikat", df.duplicated().sum())

Jumlah data duplikat 8

In [31]:
# TODO: df = df.drop_duplicates()  — lalu cetak len(df)
df = df.drop_duplicates(keep="first")
print("Jumlah data duplikat", df.duplicated().sum())

Jumlah data duplikat 0

## 5. Standarkan format

In [32]:
# TODO: cetak df["category"].value_counts(). Apa yang bisa kita amati di sini ?
df["category"].value_counts()

category
Rumah           103
Makanan          95
Kesehatan        87
Elektronik       84
Fashion          79
 Elektronik       5
MAKANAN           5
KESEHATAN         5
makanan           4
 Makanan          4
 Rumah            3
kesehatan         3
fashion           3
 Kesehatan        3
ELEKTRONIK        2
elektronik        2
rumah             2
RUMAH             2
FASHION           1
Name: count, dtype: int64

In [34]:
# TODO: df["category"] = df["category"].str.lower().str.strip()
df["category"] = df["category"].str.lower().str.strip() # merubah kolom kategori menjadi huruf kecil semua, hapus whitespacenya
# Cetak value_counts lagi untuk verifikasi
df["category"].value_counts()

category
rumah         110
makanan       108
kesehatan      98
elektronik     93
fashion        83
Name: count, dtype: int64

In [35]:
# TODO: konversi order_date
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce", format="mixed")
print(df['order_date'].isna().sum())

0

In [36]:
df["order_date"]

0     2024-08-13
1     2024-03-14
2     2024-10-16
3     2024-11-22
4     2024-06-27
         ...
503   2024-07-22
504   2024-09-28
505   2024-09-15
506   2024-04-02
507   2024-10-05
Name: order_date, Length: 492, dtype: datetime64[us]

## 6. Bonus — buang noisy values (harga ≤ 0, quantity aneh, rating di luar 0–5)

In [38]:
# TODO: buat boolean mask untuk baris invalid, lalu filter
mask_bad = (
    (df["price_idr"] <= 0) | (df["quantity"] <= 0) | (df["quantity"] > 100) | (df["rating"] < 0) | (df["rating"] > 5)
)
df = df[~mask_bad].copy() # ~ tilde

## 7. Sebelum vs sesudah

In [ ]:
# TODO: print shape akhir, total null, kategori unik
print(len(df))
print(df.shape) # tipe data tuple 
print(df.isna().sum())
print(df["category"].nunique())

487
(487, 13)
order_id          0
order_date        0
customer_name     0
email             0
segment           0
city              0
category          0
product_name      0
price_idr         0
quantity          0
discount          0
rating            0
product_review    0
dtype: int64
5

In [ ]:
# TODO: simpan ke orders_cleaned_intermediate.csv
df.to_csv("../datasets/orders_cleaned_intermediate.csv", index=False)